server:
  port: 9090

spring:
  datasource:
    druid:
      name: bookManageSystem
      url: jdbc:mysql://localhost:3306/bookmanagesystem?characterEncoding=UTF-8&serverTimezone=UTC
      username: wanghao
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化物理连接个数
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间(ms)
      max-wait: 60000
      # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间(ms)
      min-evictable-idle-time-millis: 60000
      # 开启缓存preparedStatement(PSCache)
      pool-prepared-statements: false
      # 启用PSCache后，指定每个连接上PSCache的大小
      #max-pool-prepared-statement-per-connection-size: 20
      # 用来检测连接是否有效的sql
      validation-query: select 'x'
      # 申请连接时不检测连接是否有效
      test-on-borrow: false
      # 归还连接时不检测连接是否有效
      test-on-return: false
      # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
      test-while-idle: true
      # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
      filters: stat,wall
      # 支持合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.bmp,/*.png,/*.css,/*.ico,/druid/*
      #StatViewServlet配置
      stat-view-servlet:
        allow: 127.0.0.1
        enabled: true  #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        login-username: admin
        login-password: 123456
        url-pattern: /druid/*
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.model
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.dao: debug
